apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: model-server
  template:
    metadata:
      labels:
        app: model-server
    spec:
      containers:
      - name: model-server
        image: model-server:default
        ports:
        - containerPort: 5000
        env:
        - name: MODEL_PATH
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: MODEL_PATH
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
            - name: model-data
              mountPath: "/app"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readiness
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: model-data
        hostPath:
          path: "/tmp"
